In [2]:
import pandas as pd

In [3]:
bank = pd.read_csv('Bank_Marketing_Original_Data.csv')

In [4]:
bank

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [5]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        45211 non-null  int64
 1   Job        45211 non-null  object
 2   Marital    45211 non-null  object
 3   Education  45211 non-null  object
 4   Default    45211 non-null  object
 5   Balance    45211 non-null  int64
 6   Housing    45211 non-null  object
 7   Loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   Day        45211 non-null  int64
 10  Month      45211 non-null  object
 11  Duration   45211 non-null  int64
 12  Campaign   45211 non-null  int64
 13  Pdays      45211 non-null  int64
 14  Previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  TARGET     45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [6]:
bank['Job'].value_counts()

Job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [7]:
bank['Education'].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [8]:
## Ordinal Column ---> Education ---> ordinal encode
## Label Encode ---> TARGET ---> label encoder
## Nominal Column ---> Married, and all other columns ---> one hot encoder

In [9]:
## column transform ---> is advanced and that in future

In [10]:
# first separate the diff data, nominal, ordinal, etc
## and input data must be 2D format that's why [[]] double brackets

In [11]:
ordinal_data = bank[['Education']] ## education

In [12]:
ordinal_data

       Education
0       tertiary
1      secondary
2      secondary
3        unknown
4        unknown
...          ...
45206   tertiary
45207    primary
45208  secondary
45209  secondary
45210  secondary

[45211 rows x 1 columns]

## Ordinal Encoding

In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [14]:
oe = OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']])

In [15]:
ordinal_data  =  oe.fit_transform(ordinal_data)

In [16]:
ordinal_data

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [2.],
       [2.]])

In [17]:
target_data = bank[['TARGET']] ## Target column ---> label encoding

In [18]:
target_data ## we should use label encoder

      TARGET
0         no
1         no
2         no
3         no
4         no
...      ...
45206    yes
45207    yes
45208    yes
45209     no
45210     no

[45211 rows x 1 columns]

## Label Encoding

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le = LabelEncoder()

In [21]:
label_encoder = le.fit_transform(target_data)

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [22]:
label_encoder

array([0, 0, 0, ..., 1, 0, 0])

## One Hot Encoding

In [23]:
bank.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [29]:
bank['poutcome'].value_counts()

poutcome
unknown    36959
failure     4901
other       1840
success     1511
Name: count, dtype: int64

In [25]:
nominal_data = bank[['Job','Marital','Education','Default','Housing','Loan','contact','Month','poutcome']]

In [27]:
nominal_data.head()

,Job,Marital,Education,Default,Housing,Loan,contact,Month,poutcome
0,management,married,tertiary,no,yes,no,unknown,may,unknown
1,technician,single,secondary,no,yes,no,unknown,may,unknown
2,entrepreneur,married,secondary,no,yes,yes,unknown,may,unknown
3,blue-collar,married,unknown,no,yes,no,unknown,may,unknown
4,unknown,single,unknown,no,no,no,unknown,may,unknown

In [30]:
bank['Marital'].value_counts()

Marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
ohe = OneHotEncoder()

In [ ]:
nominal_data = ohe.fit_transform(nominal_data) #encoding

In [37]:
nominal_data ## all columns are converted into o's and 1's

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 406899 stored elements and shape (45211, 44)>