# Automated Data Cleaning

#### Types of Missing Data :

#### 1. Missing Compleately at Random (MCAR)
#### 2. Missing At Random (MAR)
#### 3. Missing Not At Random (MNAR)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('unclean_smartwatch_health_data.csv')

In [5]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   object
 5   Activity Level          9800 non-null   object
 6   Stress Level            9800 non-null   object
dtypes: float64(4), object(3)
memory usage: 547.0+ KB

In [7]:
df['User ID'].isnull().sum()

np.int64(201)

In [9]:
df = df.drop(columns=['User ID'])

In [13]:
df.isnull().sum()

Heart Rate (BPM)          400
Blood Oxygen Level (%)    300
Step Count                100
Sleep Duration (hours)    150
Activity Level            200
Stress Level              200
dtype: int64

In [14]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [16]:
## 400 ---> 1,2,3 which one
df[df['Heart Rate (BPM)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...
9875,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8