# Data Gather from JSON Data

In [1]:
import pandas as pd

In [2]:
pd.read_json('iris.json')

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

### Gathering SQL Data and then need to apply some analysis of want to build model on it ---> 
### library ---> mysql.connector(library helps to connect with mysql database)
### if data in sqlite formate then we use sqlite3 library

In [4]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 2.0 MB/s eta 0:00:06
     --- ------------------------------------ 1.0/11.9 MB 2.1 MB/s eta 0:00:06
     ------- -------------------------------- 2.1/11.9 MB 3.1 MB/s eta 0:00:04
     ----------- ---------------------------- 3.4/11.9 MB 3.9 MB/s eta 0:00:03
     ---------------- ----------------------- 5.0/11.9 MB 4.7 MB/s eta 0:00:02
     ----------------------- ---------------- 7.1/11.9 MB 5.5 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 6.5 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 7.2 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 6.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=247959 sha256=f75917bd319e6f34453d704ee6551ad08fd2c7ec28e3c4c22abced0e3c3b72ef
  Stored in directory: c:\users\asus\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

  DEPRECATION: Building 'mysql.connector' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'mysql.connector'. Discussion can be found at https://github.com/pypa/pip/issues/6334

### A function which can helps us connecting to our databaseis
### .connect()
### connect() ---> host ---> server ---> localhost,
### connect() ---> user ---> username
### connect() ---> password
### connect() ---> database ---> database name

In [ ]:
import mysql.connector

In [7]:
data = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [8]:
data

### to read the connent in the database table then we use
### read_sql_query()  ---->  'sql query',database connection variable

In [13]:
df = pd.read_sql_query('select * from city',data)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_27224\3839954085.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select * from city',data)

In [14]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [16]:
pd.read_sql_query('select * from city where Population > 100000',data)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_27224\1107072487.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from city where Population > 100000',data)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
3553  4074            Gaza         PSE           Gaza      353632
3554  4075      Khan Yunis         PSE     Khan Yunis      123175
3555  4076          Hebron         PSE         Hebron      119401
3556  4077        Jabaliya         PSE     North Gaza      113901
3557  4078          Nablus         PSE         Nablus      100231

[3558 rows x 5 columns]

In [18]:
ind = pd.read_sql_query('select * from city where CountryCode like "IND"',data)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_27224\2440504096.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ind = pd.read_sql_query('select * from city where CountryCode like "IND"',data)

In [19]:
ind

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [21]:
pd.read_sql_query('select * from country where LifeExpectancy > 80',data)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_27224\1837881463.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from country where LifeExpectancy > 80',data)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
1,JPN,Japan,Asia,Eastern Asia,377829.0,-660.0,126714000,80.7,3787042.0,4192638.0,Nihon/Nippon,Constitutional Monarchy,Akihito,1532,JP
2,MAC,Macao,Asia,Eastern Asia,18.0,NaN,473000,81.6,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454,MO
3,SGP,Singapore,Asia,Southeast Asia,618.0,1965.0,3567000,80.1,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208,SG
4,SMR,San Marino,Europe,Southern Europe,61.0,885.0,27000,81.1,510.0,NaN,San Marino,Republic,None,3171,SM